### ISSUE TITLE
Error downloading video

### ISSUE THREAD

**Issue by nandadytm** [alzamer2/Crunchyroll-XML-Decoder#6]
I'm getting this message when I added the link (using choice 1) and after Booting up it show this message : 

```
Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 425, in <module>
    makechoise()
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 358, in makechoise
    ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 303, in ultimate
    video_hls(filen, video_input, connection_n_)
  File "crunchy-xml-decoder\hls.py", line 270, in video_hls
    fetch_encryption_key(video)
  File "crunchy-xml-decoder\hls.py", line 255, in fetch_encryption_key
    video.keys[0].key_value = urllib2.urlopen(url = video.keys[0].uri).read()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Press any key to continue . . .
```

Can't figure out what's wrong, I can download subtitle just fine

**Comment by alzamer2** [comment]
can you type the link that you used here?

**Comment by alzamer2** [comment]
what version of Python are you using

**Comment by nandadytm** [comment]
I'm using :

`Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32`

**Comment by alzamer2** [comment]
try to download Python 2.7.9 x86 (32bit)

if did not work download this file and replace the one in dirctary 
[crunchy-xml-decoder.bat.txt](https://github.com/alzamer2/Crunchyroll-XML-Decoder/files/978331/crunchy-xml-decoder.bat.txt)
remember to remove txt at end of the file
and tell me what happen with you

**Comment by alzamer2** [comment]
if still not work try this portable  version
https://mega.nz/#!goNABAaC!YO93PW0-2IaOioEiapPFDnthY8dWC09H5FWk3UfVhQU

**Comment by nandadytm** [comment]
I installed python 2.7.9 32 bit version, doesn't work (problem still happening).
Tried the new bat file and the portable version too, still not working.

```
python version=2.7.9 32 bit
OS Version=Windows 2012Server 6.2.9200
System Type=AMD64
Crypto installed
lxml installed
Cfscrape installed
m3u8 installed
User Name=u:********
Membership Type=Premium Member
Options:
0.- Exit
1.- Download Anime
2.- Download Subtitle only
3.- Login
4.- Login As Guest
5.- Download an entire Anime(Autocatch links)
6.- Run Queue
7.- Settings

> 1
Please enter Crunchyroll video URL:
http://www.crunchyroll.com/clockwork-planet/episode-5-trishula-734227

--------------------------
---- Start New Export ----
--------------------------

CrunchyRoll Downloader Toolkit DX v0.98b

Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.

----------
Booting up...

Now Downloading - Clockwork Planet Episode 5 - Trishula
Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 425, in <module>
    makechoise()
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder.py", line 358, in makechoise
    ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 303, in ultimate
    video_hls(filen, video_input, connection_n_)
  File "crunchy-xml-decoder\hls.py", line 270, in video_hls
    fetch_encryption_key(video)
  File "crunchy-xml-decoder\hls.py", line 255, in fetch_encryption_key
    video.keys[0].key_value = urllib2.urlopen(url = video.keys[0].uri).read()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Press any key to continue . . .
```

This is the full log from the command line.

**Comment by alzamer2** [comment]
ok i want to try something but it will take like full day wait for me

**Comment by alzamer2** [comment]
Just want to make sure
You downloaded node.js right?

**Comment by nandadytm** [comment]
of course... it won't run without it anyway

**Comment by alzamer2** [comment]
try replacing hls,py in crunchy-xml-decoder with this file and see what happen
[hls.py.txt](https://github.com/alzamer2/Crunchyroll-XML-Decoder/files/980786/hls.py.txt)


dont forget to remove txt at end of the file

**Comment by nandadytm** [comment]
Tested it with zipped clone version. It's working normally now.
